apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eventbook-ingress
  namespace: eventbook
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx

  tls:
    - hosts:
        - www.eventbook.name.ng
      secretName: eventbook-tls

  rules:
    - host: www.eventbook.name.ng
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80