apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: eventbook
type: Opaque
stringData:
  POSTGRES_DB: eventbook
  POSTGRES_USER: YOUR-USERNAME
  POSTGRES_PASSWORD: YOUR PASSWORD